apiVersion: v1
kind: ConfigMap
metadata:
  # State metrics from kube-state-metrics service:
  name: metricbeat-deployment-modules
  namespace: elk
  labels:
    k8s-app: metricbeat
    kubernetes.io/cluster-service: "true"
data:
  # https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kubernetes.html
  # This module requires `kube-state-metrics` up and running under `elk` namespace
  kubernetes.yml: |-
    - module: kubernetes
      enabled: true
      period: 10m
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
      hosts: ["kube-state-metrics.kube-system:8080"]

    # Kubernetes events
    - module: kubernetes
      enabled: true
      period: 10m
      metricsets:
        - event
