apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
  labels:
    k8s-app: logstash
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
